import React from 'react';
import { ChecklistItem, DiscussionContent } from '../types';
import { Download, FileText, Printer } from 'lucide-react';

import ReactMarkdown from 'react-markdown';
import { MarketDataChart, SalesFunnelDiagram } from './Visuals';

interface ReportProps {
  checklist: ChecklistItem[];
  discussions: DiscussionContent[];
}

export const Report: React.FC<ReportProps> = ({ checklist, discussions }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-ivory text-obsidian p-12 max-w-4xl mx-auto shadow-2xl print:shadow-none print:p-0">
      <header className="border-b-4 border-obsidian pb-8 mb-12 flex justify-between items-end">
        <div>
          <h1 className="text-5xl font-serif font-bold italic uppercase tracking-tighter">Strategic Audit</h1>
          <p className="font-mono text-xs mt-2 uppercase tracking-widest opacity-60">Elite Business Consultant Framework</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-bold">Date: {new Date().toLocaleDateString()}</p>
          <p className="text-xs opacity-60">Ref: EBC-2025-001</p>
        </div>
      </header>

      <section className="mb-12">
        <h2 className="text-2xl font-serif font-bold border-b border-obsidian/20 pb-2 mb-6">Executive Checklist</h2>
        <div className="grid grid-cols-2 gap-x-12 gap-y-4">
          {checklist.map((item) => (
            <div key={item.id} className="flex items-center gap-3">
              <div className={`w-4 h-4 border border-obsidian flex items-center justify-center ${item.status === 'completed' ? 'bg-obsidian' : ''}`}>
                {item.status === 'completed' && <div className="w-2 h-2 bg-ivory" />}
              </div>
              <div>
                <p className="text-sm font-bold leading-tight">{item.title}</p>
                <p className="text-[10px] opacity-60 uppercase tracking-widest">{item.category}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-12">
        <h2 className="text-2xl font-serif font-bold border-b border-obsidian/20 pb-2 mb-6">Strategic Insights</h2>
        {discussions.map((disc) => (
          <div key={disc.id} className="break-inside-avoid">
            <h3 className="text-xl font-serif font-bold italic mb-4">{disc.title}</h3>
            <div className="text-sm leading-relaxed mb-6 opacity-80 prose prose-sm max-w-none">
              <ReactMarkdown
                components={{
                  p: ({ children }) => {
                    const childrenArray = React.Children.toArray(children);
                    
                    if (childrenArray.some(child => typeof child === 'string' && child.includes('<MarketDataChart />'))) {
                      return (
                        <div className="my-6 space-y-2">
                          <p className="font-mono text-[8px] uppercase tracking-widest opacity-40">Market Trend Visualization</p>
                          <MarketDataChart />
                        </div>
                      );
                    }

                    if (childrenArray.some(child => typeof child === 'string' && child.includes('<SalesFunnelDiagram />'))) {
                      return (
                        <div className="my-6 space-y-2">
                          <p className="font-mono text-[8px] uppercase tracking-widest opacity-40">Sales Funnel Efficiency</p>
                          <SalesFunnelDiagram />
                        </div>
                      );
                    }

                    return <p className="mb-2">{children}</p>;
                  }
                }}
              >
                {disc.content}
              </ReactMarkdown>
            </div>
            <div className="bg-obsidian/5 p-4 border-l-4 border-obsidian mb-4">
              <p className="text-xs font-bold uppercase tracking-widest mb-1">Case Study: {disc.caseStudy.title}</p>
              <p className="text-sm italic opacity-70">{disc.caseStudy.description}</p>
            </div>
          </div>
        ))}
      </section>

      <footer className="mt-20 pt-8 border-t border-obsidian/20 text-center">
        <p className="text-[10px] uppercase tracking-[0.3em] opacity-40">Generated by Elite Business Consultant Framework</p>
      </footer>

      <div className="fixed bottom-8 right-8 flex gap-4 print:hidden">
        <button 
          onClick={handlePrint}
          className="flex items-center gap-2 bg-obsidian text-ivory px-6 py-3 rounded-full shadow-xl hover:scale-105 transition-transform font-bold text-sm"
        >
          <Printer className="w-4 h-4" />
          Print Report
        </button>
      </div>
    </div>
  );
};
